version: '3'

services:
  postgres:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=url_shortener_user
      - APP_DB_PASS=LWK/36zY
      - APP_DB_NAME=url_shortener
    volumes:
      - ./docker/db-init:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432